### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by jcartw** [linux4sam/mpio#1]
ioctl.py is not compatible with Python 3 due to the `unicode` reference at: https://github.com/linux4sam/mpio/blob/c691030e2897cb285f7a3453f4db49c41921ab26/mpio/ioctl.py#L54

Updating this line to just `if isinstance(size, str):` resolves the issue.

**Comment by jcartw** [comment]
@joshua-henderson, I have an update available if you can give me permission to submit a PR.

**Comment by joshua-henderson** [comment]
@jcartw89 Thanks for the feedback.  I applied a fix.  Let me know if a0ad101b7d doesn't work for you.

**Comment by jcartw** [comment]
@joshua-henderson Thank you! We're using this python package inside a Docker container which is being installed via `pip`. Can we access this update via `pipy`?

**Comment by joshua-henderson** [comment]
@jcartw89  v1.2 pushed to PyPi.
